version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al target/

artifacts:
  files:
    - target/springboot-helloworld-0.0.1-SNAPSHOT.jar
    - Procfile
    - buildspec.yml
    - appspec.yml       # if using CodeDeploy
    - scripts/**         # if using lifecycle scripts
